import type { Opportunity } from "./types";

/**
 * SEED DATA — replace before public launch.
 *
 * These entries are illustrative examples of the kinds of things Navigate is
 * meant to surface (Durham community events, student competitions, volunteering).
 * None of them have been confirmed with an organiser, which is why every row
 * ships with `verified: false` and the page carries a standing warning.
 *
 * Dates are fixed ISO strings. Anything in the past is grouped separately by the
 * UI rather than deleted, so an editor can see what has aged out.
 */
export const opportunities: Opportunity[] = [
  {
    id: "duke-hackathon",
    title: "HackDuke",
    description:
      "Weekend hackathon on Duke's campus with tracks aimed at social impact. Beginner teams are explicitly welcome and hardware is provided.",
    category: "hackathons-tech",
    date: "2026-10-24",
    endDate: "2026-10-25",
    dateKind: "event",
    location: "Duke University, Durham",
    cost: "Free",
    eligibility: "High school and college students. Teams up to 4.",
    registrationUrl: "https://hackduke.org",
    source: "Organiser website",
    sourceUrl: "https://hackduke.org",
    verified: false,
    featured: true,
  },
  {
    id: "nc-science-olympiad",
    title: "North Carolina Science Olympiad regional",
    description:
      "Team competition across biology, chemistry, physics, and engineering build events. Registration runs through a school team, not individually.",
    category: "competitions",
    date: "2027-02-27",
    dateKind: "event",
    location: "Varies by region",
    cost: "Team registration fee",
    eligibility: "Registered school teams",
    registrationUrl: "https://sciencenc.com",
    source: "NC Science Olympiad",
    sourceUrl: "https://sciencenc.com",
    verified: false,
  },
  {
    id: "duke-research-lecture",
    title: "Public research lectures at Duke",
    description:
      "Open lecture series where faculty present current work. Good low-commitment way to see what research in a field actually looks like.",
    category: "academic-events",
    date: null,
    dateKind: "rolling",
    location: "Duke University, Durham",
    cost: "Free",
    eligibility: "Open to the public",
    registrationUrl: "https://duke.edu",
    source: "Duke events calendar",
    sourceUrl: "https://duke.edu",
    verified: false,
  },
  {
    id: "durham-food-bank",
    title: "Food Bank of Central & Eastern NC volunteer shifts",
    description:
      "Sorting and packing shifts at the Durham branch. Shifts are a few hours and count toward service hour requirements.",
    category: "volunteering",
    date: null,
    dateKind: "rolling",
    location: "Durham",
    cost: "Free",
    eligibility: "Ages 16+ unsupervised, younger with a chaperone",
    registrationUrl: "https://foodbankcenc.org",
    source: "Food Bank of Central & Eastern NC",
    sourceUrl: "https://foodbankcenc.org",
    verified: false,
    featured: true,
  },
  {
    id: "museum-life-science",
    title: "Museum of Life and Science volunteer program",
    description:
      "Teen volunteer program helping run exhibits and demonstrations. Applications open on a schedule, so check before the term starts.",
    category: "volunteering",
    date: null,
    dateKind: "rolling",
    location: "Durham",
    cost: "Free",
    eligibility: "High school students, application required",
    registrationUrl: "https://lifeandscience.org",
    source: "Museum of Life and Science",
    sourceUrl: "https://lifeandscience.org",
    verified: false,
  },
  {
    id: "durham-arts-council",
    title: "Durham Arts Council workshops",
    description:
      "Short evening and weekend workshops in printmaking, ceramics, photography, and writing. Some have student pricing.",
    category: "arts-culture",
    date: null,
    dateKind: "rolling",
    location: "Downtown Durham",
    cost: "Varies, some student rates",
    eligibility: "Open enrollment, some age minimums",
    registrationUrl: "https://durhamarts.org",
    source: "Durham Arts Council",
    sourceUrl: "https://durhamarts.org",
    verified: false,
  },
  {
    id: "diamante-scholarship",
    title: "Regional scholarship application window",
    description:
      "An example of a deadline-driven entry. Deadlines show a countdown and sort ahead of dated events on this page.",
    category: "career",
    date: "2026-12-01",
    dateKind: "deadline",
    location: "Online",
    cost: "Free to apply",
    eligibility: "North Carolina high school juniors and seniors",
    registrationUrl: null,
    source: "Seed example — replace with a real listing",
    verified: false,
  },
  {
    id: "american-underground",
    title: "Student startup meetups in downtown Durham",
    description:
      "Evening meetups and demo nights at Durham's startup hub. Mostly college and founder crowd, generally open to high schoolers.",
    category: "entrepreneurship",
    date: null,
    dateKind: "rolling",
    location: "Downtown Durham",
    cost: "Free",
    eligibility: "Open, check individual events",
    registrationUrl: "https://americanunderground.com",
    source: "American Underground",
    sourceUrl: "https://americanunderground.com",
    verified: false,
  },
  {
    id: "durham-farmers-market",
    title: "Durham Farmers' Market",
    description:
      "Saturday morning market in Central Park. An easy first trip off campus and a regular volunteer need for setup and breakdown.",
    category: "community",
    date: null,
    dateKind: "rolling",
    location: "Durham Central Park",
    cost: "Free to attend",
    eligibility: "Open to everyone",
    registrationUrl: "https://durhamfarmersmarket.com",
    source: "Durham Farmers' Market",
    sourceUrl: "https://durhamfarmersmarket.com",
    verified: false,
  },
  {
    id: "nc-state-engineering-day",
    title: "Engineering open house at NC State",
    description:
      "Lab tours and department sessions aimed at prospective students. Worth going even if you are undecided on a major.",
    category: "career",
    date: "2026-11-07",
    dateKind: "event",
    location: "NC State University, Raleigh",
    cost: "Free",
    eligibility: "High school students and families",
    registrationUrl: "https://ncsu.edu",
    source: "NC State",
    sourceUrl: "https://ncsu.edu",
    verified: false,
  },
  {
    id: "math-competition-amc",
    title: "AMC 12 competition sitting",
    description:
      "Administered on campus. Talk to the math department about registering; there is a cutoff well before the test date.",
    category: "competitions",
    date: "2026-11-12",
    dateKind: "event",
    location: "On campus",
    cost: "Covered by the school",
    eligibility: "Open to interested students, register in advance",
    registrationUrl: null,
    source: "Mathematical Association of America",
    sourceUrl: "https://maa.org",
    verified: false,
  },
  {
    id: "past-example",
    title: "Fall service day",
    description:
      "An example of an entry whose date has passed. Navigate keeps these out of the default view rather than deleting them, so editors can see what aged out.",
    category: "volunteering",
    date: "2026-09-05",
    dateKind: "event",
    location: "Durham",
    cost: "Free",
    eligibility: "All students",
    registrationUrl: null,
    source: "Seed example",
    verified: false,
  },
];
