import type { Resource } from "./types";

/**
 * The resource directory.
 *
 * GENERATED by `npm run resources:import`. Edit this file by hand, or edit the
 * spreadsheet and re-import; either works, but do not do both at once.
 *
 * Editing rules:
 *  - `officialUrl` must be the school's own address. Never mirror, proxy, or
 *    re-host content that sits behind an NCSSM login.
 *  - Set `loginRequired: true` whenever the destination asks for an NCSSM
 *    account, and let the student authenticate on that platform.
 *  - `contactEmail` is for offices and departments only, never an individual
 *    student.
 *  - `aliases` is the words a student would actually type. It is invisible on
 *    the page and exists only so search finds the row. When someone says they
 *    could not find something, add what they searched for here.
 */
export const resources: Resource[] = [
  /* ------------------------------------------------------ urgent-support */
  {
    id: "campus-safety",
    name: "Campus Safety & Security",
    description:
      "Staffed around the clock. Call for anything unsafe on campus, a locked building, or a medical situation that is not a 911 emergency.",
    aliases:
      "police, security, emergency, unsafe, scared, locked out, lost key, stolen, theft, escort at night",
    category: "urgent-support",
    officialUrl: "https://www.ncssm.edu/contact/durham-emergency-info",
    audience: "All students",
    contactNote:
      "Durham Campus Safety: 919-416-2911, dur.safety@ncssm.edu. Staffed around the clock. Call 911 first if someone is in danger.",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "counseling-urgent",
    name: "Counseling Services — urgent help",
    description:
      "Talk to a counselor when something cannot wait. Includes after-hours guidance and the on-call process for residential students.",
    aliases:
      "crisis, urgent, panic attack, suicidal, self harm, hurting myself, need someone right now, mental health emergency",
    category: "urgent-support",
    officialUrl: "https://counseling.ncssm.edu/",
    audience: "All students",
    contactNote:
      "If it cannot wait and it is out of hours, go to a Community Coordinator desk. Call or text 988 any time. Call 911 if someone is in danger.",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "health-services",
    name: "Student Health Services",
    description:
      "Nurses on campus for illness, injury, medication, and appointment scheduling. Start here before going off campus for care.",
    aliases:
      "nurse, sick, ill, infirmary, medicine, medication, meds, prescription, fever, injury, hurt, doctor, appointment",
    category: "urgent-support",
    officialUrl: "https://www.ncssm.edu/residential/safety-support/health",
    contactNote:
      "Clinic is open Monday to Friday, 8am to 4pm: clinic@ncssm.edu or 919-416-2892. Outside those hours go to a Community Coordinator desk; a CC on duty can reach the after-hours nursing line.",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ---------------------------------------------------- academic-support */
  {
    id: "canvas",
    name: "Canvas",
    description:
      "Course pages, assignments, and grades for most classes. Navigate links you straight to Canvas; it does not read or copy your coursework.",
    aliases:
      "assignments, homework, grades, coursework, class page, syllabus, due dates, lms, turn in",
    category: "academic-support",
    officialUrl: "https://ncssm.instructure.com",
    audience: "All students",
    loginRequired: true,
    platform: "canvas",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "tutorial-center",
    name: "Peer tutoring",
    description:
      "Free subject tutoring from other students. Check the schedule for which subjects are covered on which nights.",
    aliases:
      "tutor, tutoring, help with homework, study help, math help, physics help, chemistry help, struggling in class",
    category: "academic-support",
    officialUrl: "https://caas.ncssm.edu/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "writing-center",
    name: "Writing Center",
    description:
      "Book a session for essays, lab reports, research papers, and college application writing.",
    aliases:
      "essay, paper, proofread, edit my essay, college essay, lab report, revise, feedback on writing",
    category: "academic-support",
    officialUrl: "https://caas.ncssm.edu/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "library",
    name: "NCSSM Library",
    description:
      "Catalog, research databases, interlibrary loan, and quiet study space. Databases ask for your NCSSM account.",
    aliases:
      "books, research, databases, journals, citation, sources, quiet study, study room",
    category: "academic-support",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/durham-library",
    audience: "All students",
    loginRequired: true,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ------------------------------------------------- advising-counseling */
  {
    id: "counseling-services",
    name: "Counseling Services",
    description:
      "Scheduled, confidential appointments for stress, homesickness, conflict, and anything else you want to talk through.",
    aliases:
      "counselor, therapist, therapy, mental health, stress, stressed, anxiety, anxious, depressed, homesick, overwhelmed, burnout, lonely, someone to talk to",
    category: "advising-counseling",
    officialUrl: "https://counseling.ncssm.edu/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "college-counseling",
    name: "College Counseling",
    description:
      "Your college counselor, application deadlines, transcript requests, and recommendation letter timelines.",
    aliases:
      "college applications, common app, college apps, recommendation letter, rec letter, sat, act, deadlines, early decision, where to apply",
    category: "advising-counseling",
    officialUrl: "https://www.ncssm.edu/residential/safety-support/counseling/college-career-planning",
    audience: "Juniors and seniors",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "academic-advising",
    name: "Academic advising",
    description:
      "Course selection, schedule changes, add/drop windows, and graduation requirement questions.",
    aliases:
      "schedule change, drop a class, add a class, course selection, registration, graduation requirements, credits, what classes to take",
    category: "advising-counseling",
    officialUrl: "https://www.ncssm.edu/residential/academics/courses",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ---------------------------------------------------- residential-life */
  {
    id: "residential-life",
    name: "Residential Life",
    description:
      "Who your RLA and Community Coordinator are, hall expectations, room changes, and how the residential day is structured.",
    aliases:
      "dorm, hall, rli, roommate, room change, curfew, lights out, residential, living on campus",
    category: "residential-life",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/housing-dining",
    contactNote:
      "Your hall is covered by RLAs (student leaders) and a Community Coordinator, the adult who lives next to the halls. Start with them for anything about the hall.",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "maintenance-request",
    name: "Facilities & maintenance request",
    description:
      "Report a broken light, a stuck window, heating or cooling problems, and anything else physically wrong with your room or hall.",
    aliases:
      "broken, repair, fix, work order, heat, heating, ac, air conditioning, radiator, light out, leak, flooding, toilet, sink, facilities, laundry machine, dryer, washer",
    category: "residential-life",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/housing-dining",
    contactNote:
      "Your hall is covered by RLAs (student leaders) and a Community Coordinator, the adult who lives next to the halls. Start with them for anything about the hall.",
    audience: "Residential students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "laundry-mail",
    name: "Mail room & package pickup",
    description:
      "Where packages go, pickup hours, and how to address mail so it reaches you.",
    aliases:
      "package, packages, mail, amazon, delivery, mailroom, shipping address",
    category: "residential-life",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/housing-dining",
    contactNote:
      "Laundry rooms are in the residence halls and the machines take a small fee.",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ----------------------------------------------- dining-transportation */
  {
    id: "dining-menu",
    name: "Dining hall menus & hours",
    description:
      "What is being served, when the dining hall is open, and how to flag an allergy or dietary need.",
    aliases:
      "food, dining hall, cafeteria, menu, meal, meals, allergy, allergies, vegetarian, vegan, gluten, breakfast, lunch, dinner, dining hours",
    category: "dining-transportation",
    officialUrl: "https://ncssm-durham.campus-dining.com/",
    contactNote:
      "Meals are free to students. Vegetarian, vegan, and gluten-free options are provided; talk to dining staff about an allergy so it is on file.",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "bus-transportation",
    name: "Student transportation & break buses",
    description:
      "Bus schedules for breaks, pickup points across North Carolina, and how to reserve a seat.",
    aliases:
      "bus, buses, ride home, break bus, shuttle, getting home, travel home, pickup, drop off",
    category: "dining-transportation",
    officialUrl: "https://www.ncssm.edu/residential/campus-life",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "durham-transit",
    name: "GoDurham transit",
    description:
      "Public bus routes and live arrival times around Durham. Useful for getting to volunteering and community events off campus.",
    aliases:
      "godurham, city bus, public transit, bus route, getting around durham",
    category: "dining-transportation",
    officialUrl: "https://godurhamtransit.org",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ---------------------------------------------------------- technology */
  {
    id: "it-helpdesk",
    name: "Information Technology Services (ITS)",
    description:
      "Laptop problems, wifi that will not connect, printing, and account lockouts. Start here before anything else tech related.",
    aliases:
      "its, technology office, tech help, computer help, software, network, printing, accounts, charger, equipment",
    category: "technology",
    officialUrl: "https://www.ncssm.edu/information-technology-services",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "ncssm-email",
    name: "NCSSM email & Google Workspace",
    description:
      "Your school email, Drive, Docs, and Calendar. Navigate links you to Google's own sign-in; it never sees your password or your files.",
    aliases:
      "gmail, email, inbox, google drive, docs, sheets, slides, calendar, workspace",
    category: "technology",
    officialUrl: "https://mail.google.com",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "blackbaud",
    name: "Student information system",
    description:
      "Schedule, attendance, report cards, and permissions. This is the system most official student records live in.",
    aliases:
      "myschoolapp, sis, student portal, report card, attendance, my schedule, grades, transcript view",
    category: "technology",
    officialUrl: "https://ncssm.myschoolapp.com",
    audience: "All students",
    loginRequired: true,
    platform: "blackbaud",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "wifi",
    name: "Campus wifi setup",
    description:
      "Which network to join, how to register a personal device, and what to do when a device keeps dropping off.",
    aliases:
      "internet, network, wifi password, connect to wifi, eduroam, register device, xbox, console, tv",
    category: "technology",
    officialUrl: "https://www.ncssm.edu/information-technology-services",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* --------------------------------------------------------------- forms */
  {
    id: "transcript-request",
    name: "Transcript request",
    description:
      "Request an official transcript for colleges, summer programs, and scholarship applications.",
    aliases:
      "transcript, official transcript, records, registrar, send my grades, school records",
    category: "forms",
    officialUrl: "https://sites.google.com/ncssm.edu/registrar",
    audience: "All students and alumni",
    loginRequired: true,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "club-charter",
    name: "Club charter & renewal form",
    description:
      "Start a new club or renew an existing one for the year, including advisor sign-off.",
    aliases:
      "start a club, new club, charter a club, club renewal, found a club",
    category: "forms",
    officialUrl: "https://www.ncssm.edu/residential/activities-clubs",
    audience: "Club officers",
    loginRequired: true,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "funding-request",
    name: "Student activity funding request",
    description:
      "Ask for funding for a club event, competition travel, or supplies. Read the deadline before you start.",
    aliases:
      "money, funding, budget, reimbursement, club money, pay for, buy supplies, travel funding",
    category: "forms",
    officialUrl: "https://www.ncssm.edu/residential/activities-clubs",
    audience: "Club officers",
    loginRequired: true,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* -------------------------------------------------------- student-life */
  {
    id: "clubs-directory",
    name: "Clubs & organizations",
    description:
      "The full list of chartered clubs, who leads them, and when they meet.",
    aliases:
      "clubs, organizations, activities, join a club, extracurriculars, what clubs exist",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/residential/activities-clubs",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "athletics",
    name: "Athletics & intramurals",
    description:
      "Team rosters, practice times, game schedules, and how to join an intramural league mid-season.",
    aliases:
      "sports, team, tryouts, gym, weight room, intramural, practice, workout, fitness",
    category: "student-life",
    officialUrl: "https://www.gounis.com/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "campus-calendar",
    name: "Campus calendar",
    description:
      "Academic dates, breaks, exam windows, and all-school events in one calendar.",
    aliases:
      "calendar, important dates, breaks, spring break, exams, finals, when is",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/about/events",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* -------------------------------------------------- student-government */
  {
    id: "sg-contact",
    name: "Contact Student Government",
    description:
      "Reach SG directly about anything Navigate does not cover, including things you would rather say to a person.",
    aliases:
      "student government, sg, senate, contact sg, talk to sg",
    category: "student-government",
    officialUrl: "/sg",
    audience: "All students",
    loginRequired: false,
    platform: "email",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "sg-report-issue",
    name: "Report an issue to SG",
    description:
      "Submit a concern about academics, housing, dining, transport, tech, or accessibility. You can submit anonymously.",
    aliases:
      "complain, complaint, report a problem, issue, suggestion, feedback, something is wrong",
    category: "student-government",
    officialUrl: "/report",
    audience: "All students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "sg-updates-link",
    name: "SG issue status board",
    description:
      "See what SG is working on right now and where each item stands, without any private details.",
    aliases:
      "status, progress, what is sg doing, updates, is anyone fixing",
    category: "student-government",
    officialUrl: "/updates",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },

  /* ---------------------------------------------------- added from the
     NCSSM site's own page tree. Every URL here was opened and returned 200,
     but nobody at the school has confirmed each is the best destination for
     what the row promises, so they stay needs-review. */

  {
    id: "staff-directory",
    name: "Faculty & staff directory",
    description:
      "Search for any staff member and get their role and email. The fastest answer to “who do I actually email about this”.",
    aliases:
      "who do i email, contact a teacher, staff email, find a teacher, phone number, department contact, who handles",
    category: "student-government",
    officialUrl: "https://www.ncssm.edu/about/directory",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "wellness-counseling",
    name: "Wellness counseling",
    description:
      "The counseling team's page for ongoing mental-health support: what they do, who they are, and how to start.",
    aliases:
      "therapy, therapist, mental health, anxiety, depression, stress, counseling appointment, talk to someone, wellness",
    category: "advising-counseling",
    officialUrl:
      "https://www.ncssm.edu/residential/safety-support/counseling/wellness-counseling",
    contactNote:
      "For something that cannot wait out of hours, go to a Community Coordinator desk, or call or text 988.",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "accessibility-services",
    name: "Accessibility services",
    description:
      "Academic accommodations, documentation, and who to talk to about getting support in place.",
    aliases:
      "accommodations, 504, iep, extra time, testing accommodations, disability, accessibility, learning support, adhd",
    category: "advising-counseling",
    officialUrl:
      "https://www.ncssm.edu/residential/safety-support/counseling/accessibility",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "title-ix",
    name: "Title IX",
    description:
      "Reporting and support for sex discrimination, harassment, and sexual misconduct, including who the coordinator is.",
    aliases:
      "harassment, sexual harassment, assault, discrimination, title 9, report misconduct, coordinator",
    category: "urgent-support",
    officialUrl: "https://accessibility.ncssm.edu/",
    contactNote:
      "This is a formal reporting route with people trained for it. Navigate is not, and an issue like this should never go through the report form.",
    audience: "All students",
    loginRequired: false,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "lgbtq-resources",
    name: "LGBTQ+ resource guide",
    description:
      "NCSSM's guide to support, groups, and points of contact for LGBTQ+ students.",
    aliases:
      "lgbtq, lgbt, queer, trans, transgender, gay, pronouns, gsa, support group, coming out",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/lgbtq-resource-guide",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "course-catalog",
    name: "Durham course catalog",
    description:
      "Every course offered on the Durham campus, with descriptions and prerequisites. Use it before registration, not after.",
    aliases:
      "courses, course catalog, what classes, prerequisites, class list, registration, pick classes, electives",
    category: "academic-support",
    officialUrl: "https://courses.ncssm.edu/course_catalog.php?id=1",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "student-research",
    name: "Research & innovation",
    description:
      "Mentored research, the research course sequence, and how students get placed with a lab or mentor.",
    aliases:
      "research, lab, mentorship, mentor, science fair, independent study, publish, internship",
    category: "academic-support",
    officialUrl: "https://research-innovation.ncssm.edu/home",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "service-learning",
    name: "Service learning",
    description:
      "How NCSSM's service requirement works, what counts, and where to log hours.",
    aliases:
      "service hours, volunteering, community service, requirement, log hours, graduation requirement",
    category: "student-life",
    officialUrl: "https://sites.google.com/a/ncssm.edu/service-learning/contact",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "student-media",
    name: "Student media",
    description:
      "The student publications and media groups, and how to join or submit to them.",
    aliases:
      "newspaper, yearbook, magazine, journalism, radio, podcast, photography, write for, submit",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/residential/student-media",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "fine-arts",
    name: "Fine arts",
    description:
      "Music, theatre, and visual arts at NCSSM: ensembles, productions, and how to take part.",
    aliases:
      "art, music, band, orchestra, choir, theatre, theater, drama, play, ensemble, audition, studio",
    category: "student-life",
    officialUrl: "https://sites.google.com/ncssm.edu/ncssmfinearts",
    audience: "All students",
    loginRequired: false,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "unc-guaranteed-admission",
    name: "UNC System guaranteed admission",
    description:
      "What NCSSM graduates are guaranteed within the UNC System, and the conditions attached.",
    aliases:
      "unc, guaranteed admission, in state college, state school, apply unc, chapel hill, nc state",
    category: "advising-counseling",
    officialUrl:
      "https://www.ncssm.edu/residential/unc-system-guaranteed-admission",
    audience: "Juniors and seniors",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "unc-tuition-grant",
    name: "UNC System tuition grant",
    description:
      "The tuition grant NCSSM graduates can receive at UNC System schools, and what qualifies.",
    aliases:
      "tuition grant, scholarship, financial aid, money for college, free tuition, pay for college",
    category: "advising-counseling",
    officialUrl: "https://www.ncssm.edu/residential/unc-system-tuition-grant",
    audience: "Juniors and seniors",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "college-credit",
    name: "College credit agreements",
    description:
      "Which NCSSM courses transfer for college credit and where those agreements apply.",
    aliases:
      "college credit, transfer credit, ap credit, dual enrollment, does this count, credit agreement",
    category: "academic-support",
    officialUrl:
      "https://www.ncssm.edu/residential/academics/college-credit-agreements",
    audience: "Juniors and seniors",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "emergency-procedures",
    name: "Emergency procedures & alerts",
    description:
      "What happens in a lockdown, tornado, or other emergency, plus the AED and emergency phone maps.",
    aliases:
      "emergency, lockdown, tornado, fire, evacuation, alert, aed, drill, severe weather, what do i do",
    category: "urgent-support",
    officialUrl: "https://www.ncssm.edu/contact/durham-emergency-info",
    contactNote:
      "Durham Campus Safety: 919-416-2911. Call 911 first if someone is in danger.",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "spirit-store",
    name: "Spirit store",
    description:
      "Official NCSSM clothing and merchandise.",
    aliases: "merch, hoodie, sweatshirt, shirt, store, spirit wear, unicorns, gear",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/spirit-store",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },

  /* ------------------------------------------------- the systems students
     actually use day to day, supplied by SG. These are the destinations
     that matter most: a marketing page about counseling is not the same
     thing as the link that books a clinic appointment. */

  {
    id: "orah",
    name: "Orah — sign-out & leave",
    description:
      "The system NCSSM actually uses to request leave, sign out, and check in. Submit before you go, not after.",
    aliases:
      "sign out, signout, orah, leave campus, weekend leave, going home, check in, check out, permission, day leave, overnight",
    category: "residential-life",
    officialUrl: "https://app.orah.com/login",
    audience: "All students",
    loginRequired: true,
    platform: "other",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "absence-request",
    name: "Absence request form",
    description:
      "Request an excused absence from class through the school's service desk.",
    aliases:
      "absence, miss class, excused absence, absent, skip class, sick note, cannot attend, miss a day",
    category: "forms",
    officialUrl: "https://ncssm.atlassian.net/servicedesk/customer/portal/11/group/29/create/122",
    audience: "All students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "helpdesk-ticket",
    name: "Submit a helpdesk ticket",
    description:
      "The IT service desk. File a ticket for a broken laptop, account trouble, software, or anything network related.",
    aliases:
      "it ticket, helpdesk, help desk, laptop broken, computer broken, computer problem, tech support, wifi not working, internet down, no wifi, printer not working, locked out of my account, broken screen, it help",
    category: "technology",
    officialUrl: "https://ncssm.atlassian.net/servicedesk/customer/portal/1",
    audience: "All students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "change-password",
    name: "Change your NCSSM password",
    description:
      "Reset or change the password on your NCSSM account.",
    aliases:
      "password, reset password, change password, forgot password, locked out, account locked, new password",
    category: "technology",
    officialUrl: "https://password.ncssm.edu/pwm/private/login",
    audience: "All students",
    loginRequired: true,
    platform: "other",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "tech-requirements",
    name: "Tech requirements & laptop specs",
    description:
      "What laptop you need, the specs that are supported, and what IT expects you to arrive with.",
    aliases:
      "laptop specs, what laptop, computer requirements, buy a laptop, tech requirements, minimum specs",
    category: "technology",
    officialUrl: "https://ncssm.atlassian.net/wiki/spaces/ITS/pages/71303203/Tech+requirements+and+laptop+specs",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "its-acceptable-use",
    name: "ITS acceptable use regulation",
    description:
      "The rules for using NCSSM's network, accounts, and devices.",
    aliases:
      "acceptable use, network policy, it policy, internet policy, computer policy, aup, device policy, wifi policy",
    category: "technology",
    officialUrl: "https://drive.google.com/file/d/17UBxCGrQACNrPP_0kJYvj6NTDXuY-DIw/view",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "care-report",
    name: "CARE report — concern about a student",
    description:
      "Raise a concern about a student who may be struggling, to the people trained to respond to it.",
    aliases:
      "worried about a friend, concerned, someone is struggling, mental health concern, care team, report a concern, help a friend, wellbeing",
    category: "urgent-support",
    officialUrl: "https://ncssm-advocate.symplicity.com/care_report/index.php/pid992479",
    contactNote:
      "Use this rather than Navigate for anything about a student's safety or wellbeing. It reaches staff who can actually act.",
    audience: "All students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "advocate-report",
    name: "Advocate — submit a report",
    description:
      "The school's formal reporting system for conduct, harassment, and policy violations.",
    aliases:
      "report a problem, misconduct, harassment, bullying, conduct violation, incident report, formal report, advocate",
    category: "urgent-support",
    officialUrl: "https://ncssm-advocate.symplicity.com/public_report/index.php/pid750944",
    contactNote:
      "This is the formal route with people trained for it. Navigate's issue form is not, and never should be.",
    audience: "All students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "student-handbook",
    name: "Student handbook (Durham)",
    description:
      "The rules, expectations, and procedures you are actually held to. Search it before asking whether something is allowed.",
    aliases:
      "handbook, rules, policy, what are the rules, am i allowed, student handbook, code of conduct, expectations",
    category: "forms",
    officialUrl: "https://drive.google.com/file/d/1ItwHjjNd2w4mL0pp4kHoXPq2f5fLtFLW/view",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "code-of-conduct",
    name: "Code of student conduct (policy 7110)",
    description:
      "The formal conduct policy as adopted by the Board of Trustees.",
    aliases:
      "code of conduct, discipline, consequences, policy 7110, rules, disciplinary, honor code",
    category: "forms",
    officialUrl: "https://www.ncssm.edu/about/leadership/board-of-trustees/institutional-policies",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "daily-schedule",
    name: "Daily schedule & timetable",
    description:
      "The bell schedule: when blocks run, when lunch is, and how the day is laid out.",
    aliases:
      "bell schedule, timetable, what time, class times, when does class start, lunch time, daily schedule, blocks",
    category: "academic-support",
    officialUrl: "https://docs.google.com/spreadsheets/d/1y6Rere9VTnsIOcRQ75O9sleb4jaT0QVeNRSiFdMh8X0/edit",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "academic-calendar",
    name: "Academic calendar (26-27)",
    description:
      "Term dates, breaks, exam periods, and the days school is closed.",
    aliases:
      "calendar, academic calendar, breaks, when is spring break, exam dates, term dates, holidays, last day, first day",
    category: "academic-support",
    officialUrl: "https://docs.google.com/spreadsheets/d/1wFU9AKbCzql_wdGXXwA8q9LHW5XHEoJFMPmoEsYA4lY/edit",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "monthly-calendar",
    name: "Monthly calendar (26-27)",
    description:
      "The month-by-month calendar as a single printable file.",
    aliases:
      "monthly calendar, print calendar, month view, schedule pdf, calendar pdf",
    category: "academic-support",
    officialUrl: "https://drive.google.com/file/d/1B3o_CRI0N4M8V6orahc2BPerDZTqqPS_/view",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "course-requests",
    name: "Course requests (Durham)",
    description:
      "Where course selection happens, inside Blackbaud.",
    aliases:
      "course requests, pick classes, registration, sign up for classes, course selection, choose courses, schedule request",
    category: "academic-support",
    officialUrl: "https://ncssm.myschoolapp.com/app/student?svcid=edu#resourceboarddetail/16232",
    audience: "All students",
    loginRequired: true,
    platform: "blackbaud",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "saa-durham",
    name: "Science academic assistance (Durham)",
    description:
      "Peer and staff help for science courses on the Durham campus.",
    aliases:
      "science help, chemistry help, physics help, biology help, tutoring science, saa, struggling in science",
    category: "academic-support",
    officialUrl: "https://sites.google.com/ncssm.edu/saa-durham/home",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "math-placement",
    name: "Mathematics placement",
    description:
      "How math placement works and what determines the course you start in.",
    aliases:
      "math placement, which math, placement test, calculus placement, precalc, what math class",
    category: "academic-support",
    officialUrl: "https://docs.google.com/document/u/1/d/e/2PACX-1vQlZiUyxh0V6_-5Dld5VO-Y4yPNcWmkHCIi45nT-eb2TBNUg8VUyS485UHUO5JzkMa-0IyMgX2ZvII-/pub",
    audience: "All students",
    loginRequired: false,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "ecs-placement",
    name: "Engineering & computer science placement",
    description:
      "Placement information for the engineering and computer science sequence.",
    aliases:
      "cs placement, computer science, coding class, engineering, which cs course, programming class",
    category: "academic-support",
    officialUrl: "https://ecs.ncssm.edu/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "world-language-placement",
    name: "World language placement",
    description:
      "Placement for Spanish, French, Chinese, and the other language offerings.",
    aliases:
      "language placement, spanish, french, chinese, latin, german, which language class, language test",
    category: "academic-support",
    officialUrl: "https://wlplacement.ncssm.edu/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "calculator-requirements",
    name: "Calculator requirements",
    description:
      "Which calculator you need for which course, and what is allowed in exams.",
    aliases:
      "calculator, ti 84, what calculator, graphing calculator, allowed calculator, exam calculator",
    category: "academic-support",
    officialUrl: "https://docs.google.com/document/u/1/d/e/2PACX-1vTWHQmgq8kZfZokCuGtrS97zce5rwojSGWIsstg_aylbI9mc0oYA_iXhped1vJfQvGVtwipNwphOG9_/pub",
    audience: "All students",
    loginRequired: false,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "ap-exams",
    name: "AP exam info",
    description:
      "Registration, dates, and logistics for AP exams.",
    aliases:
      "ap exam, ap test, advanced placement, register for ap, ap dates, ap scores",
    category: "academic-support",
    officialUrl: "https://sites.google.com/ncssm.edu/apexams/home",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "fablab",
    name: "FabLab",
    description:
      "The fabrication lab: equipment, training, and access for student projects.",
    aliases:
      "fablab, 3d printer, laser cutter, makerspace, build something, machine shop, prototyping, woodshop",
    category: "student-life",
    officialUrl: "https://fablab.ncssm.edu/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "clinic-appointments",
    name: "Clinic appointments (Durham)",
    description:
      "Book a time at the Durham student health clinic.",
    aliases:
      "clinic appointment, see the nurse, book clinic, health appointment, medical appointment, sick",
    category: "urgent-support",
    officialUrl: "https://sites.google.com/ncssm.edu/healthandwellness/student-health/durham-student-health-clinic",
    contactNote:
      "Clinic hours are Monday to Friday, 8am to 4pm. Outside those hours go to a Community Coordinator desk.",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "resiliency-resources",
    name: "Resiliency resources",
    description:
      "Practical resources for coping, stress, and looking after yourself during a hard stretch.",
    aliases:
      "stress, coping, burnout, overwhelmed, self care, resilience, mental health resources, anxious, struggling",
    category: "advising-counseling",
    officialUrl: "https://sites.google.com/ncssm.edu/ncssmresiliencyresources/home",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "housing-site",
    name: "Housing (Durham)",
    description:
      "Room assignments, move-in, what to bring, and residential logistics.",
    aliases:
      "housing, room assignment, move in, what to bring, dorm, roommate, room change, packing list",
    category: "residential-life",
    officialUrl: "https://sites.google.com/ncssm.edu/ncssmhousing/",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "preflight-checklist",
    name: "NCSSM-Durham pre-flight checklist",
    description:
      "The checklist of everything to sort before arriving on campus.",
    aliases:
      "checklist, before i arrive, move in checklist, what do i need, preflight, new student, forms to complete",
    category: "forms",
    officialUrl: "https://drive.google.com/file/d/1zgKshQaWxrx8RikGw5uh0wfFEfyTZgKT/view",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "security-deposit",
    name: "Security deposit payment",
    description:
      "Pay the residential security deposit online.",
    aliases:
      "deposit, security deposit, pay deposit, payment, fee",
    category: "forms",
    officialUrl: "https://osp.osmsinc.com/NCSSM/BVModules/CategoryTemplates/Detailed%20List%20with%20Properties/Category.aspx?categoryid=GR001",
    audience: "All students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "financial-assistance",
    name: "Financial assistance",
    description:
      "Help with costs: what NCSSM covers, what it does not, and what support is available.",
    aliases:
      "financial aid, money, cost, cannot afford, fee waiver, assistance, help paying, free",
    category: "forms",
    officialUrl: "https://www.ncssm.edu/admissions/financial-assistance",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "schoolinks",
    name: "SchooLinks",
    description:
      "The college and career planning platform: applications, transcripts requests, and deadlines.",
    aliases:
      "college applications, schoolinks, apply to college, transcript request, common app, college list, naviance",
    category: "advising-counseling",
    officialUrl: "https://app.schoolinks.com/login/k12",
    audience: "All students",
    loginRequired: true,
    platform: "other",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "medical-forms",
    name: "Medical form upload",
    description:
      "Where to upload immunisation and medical paperwork, inside Blackbaud.",
    aliases:
      "medical form, immunization, vaccine record, health form, upload medical, physical form",
    category: "forms",
    officialUrl: "https://ncssm.myschoolapp.com/app/student?svcid=edu#resourceboarddetail/16941",
    audience: "All students",
    loginRequired: true,
    platform: "blackbaud",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "forms-contracts",
    name: "Forms and contracts instructions",
    description:
      "How to complete and submit the school's forms and contracts.",
    aliases:
      "forms, contracts, how to submit, paperwork, signature, sign a form",
    category: "forms",
    officialUrl: "https://ncssm.atlassian.net/wiki/spaces/ITS/pages/39059493/Forms+and+Contracts+Instructions",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "science-course-info",
    name: "Science course info (Durham)",
    description:
      "Which science courses run, their sequence, and what each expects.",
    aliases:
      "science courses, which science, biology, chemistry, physics, science sequence, science requirement",
    category: "academic-support",
    officialUrl: "https://drive.google.com/file/d/1f6z-nEdUbMqgzOOrZ18OjkCH1LlT97cg/view",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "summer-science",
    name: "Summer science course",
    description:
      "Details for the summer science course requirement.",
    aliases:
      "summer course, summer science, summer work, before junior year, summer assignment",
    category: "academic-support",
    officialUrl: "https://docs.google.com/document/d/1U7I5dFEVc09RWLgsoTnTgYrmxQHPTb4O1uDWS1Ya_cg/edit",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "security-training",
    name: "Security awareness training",
    description:
      "The required IT security training.",
    aliases:
      "security training, knowbe4, phishing training, required training, cyber training",
    category: "technology",
    officialUrl: "https://training.knowbe4.com/app/login",
    audience: "All students",
    loginRequired: true,
    platform: "other",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
];
