import type { Resource } from "./types";

/**
 * The resource directory.
 *
 * GENERATED by `npm run resources:import`. Edit this file by hand, or edit the
 * spreadsheet and re-import; either works, but do not do both at once.
 *
 * Editing rules:
 *  - `officialUrl` must be the school's own address. Never mirror, proxy, or
 *    re-host content that sits behind an NCSSM login.
 *  - Set `loginRequired: true` whenever the destination asks for an NCSSM
 *    account, and let the student authenticate on that platform.
 *  - `contactEmail` is for offices and departments only, never an individual
 *    student.
 *  - `aliases` is the words a student would actually type. It is invisible on
 *    the page and exists only so search finds the row. When someone says they
 *    could not find something, add what they searched for here.
 */
export const resources: Resource[] = [
  /* ------------------------------------------------------ urgent-support */
  {
    id: "campus-safety",
    name: "Campus Safety & Security",
    description:
      "Staffed around the clock. Call for anything unsafe on campus, a locked building, or a medical situation that is not a 911 emergency.",
    aliases:
      "police, security, emergency, unsafe, scared, locked out, lost key, stolen, theft, escort at night",
    category: "urgent-support",
    officialUrl: "https://www.ncssm.edu/contact/durham-emergency-info",
    audience: "All students",
    contactNote:
      "Durham Campus Safety: 919-416-2911, dur.safety@ncssm.edu. Staffed around the clock. Call 911 first if someone is in danger.",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "counseling-urgent",
    name: "Counseling Services — urgent help",
    description:
      "Talk to a counselor when something cannot wait. Includes after-hours guidance and the on-call process for residential students.",
    aliases:
      "crisis, urgent, panic attack, suicidal, self harm, hurting myself, need someone right now, mental health emergency",
    category: "urgent-support",
    officialUrl: "https://dur-counseling.ncssm.edu",
    audience: "All students",
    contactNote:
      "If it cannot wait and it is out of hours, go to a Community Coordinator desk. Call or text 988 any time. Call 911 if someone is in danger.",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "health-services",
    name: "Student Health Services",
    description:
      "Nurses on campus for illness, injury, medication, and appointment scheduling. Start here before going off campus for care.",
    aliases:
      "nurse, sick, ill, infirmary, medicine, medication, meds, prescription, fever, injury, hurt, doctor, appointment",
    category: "urgent-support",
    officialUrl: "https://www.ncssm.edu/residential/safety-support/health",
    contactNote:
      "Clinic is open Monday to Friday, 8am to 4pm: clinic@ncssm.edu or 919-416-2892. Outside those hours go to a Community Coordinator desk; a CC on duty can reach the after-hours nursing line.",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ---------------------------------------------------- academic-support */
  {
    id: "canvas",
    name: "Canvas",
    description:
      "Course pages, assignments, and grades for most classes. Navigate links you straight to Canvas; it does not read or copy your coursework.",
    aliases:
      "assignments, homework, grades, coursework, class page, syllabus, due dates, lms, turn in",
    category: "academic-support",
    officialUrl: "https://ncssm.instructure.com",
    audience: "All students",
    loginRequired: true,
    platform: "canvas",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "tutorial-center",
    name: "Peer tutoring",
    description:
      "Free subject tutoring from other students. Check the schedule for which subjects are covered on which nights.",
    aliases:
      "tutor, tutoring, help with homework, study help, math help, physics help, chemistry help, struggling in class",
    category: "academic-support",
    officialUrl: "https://caas.ncssm.edu/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "writing-center",
    name: "Writing Center",
    description:
      "Book a session for essays, lab reports, research papers, and college application writing.",
    aliases:
      "essay, paper, proofread, edit my essay, college essay, lab report, revise, feedback on writing",
    category: "academic-support",
    officialUrl: "https://caas.ncssm.edu/",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "library",
    name: "NCSSM Library",
    description:
      "Catalog, research databases, interlibrary loan, and quiet study space. Databases ask for your NCSSM account.",
    aliases:
      "books, research, databases, journals, citation, sources, quiet study, study room",
    category: "academic-support",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/durham-library",
    audience: "All students",
    loginRequired: true,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ------------------------------------------------- advising-counseling */
  {
    id: "counseling-services",
    name: "Counseling Services",
    description:
      "Scheduled, confidential appointments for stress, homesickness, conflict, and anything else you want to talk through.",
    aliases:
      "counselor, therapist, therapy, mental health, stress, stressed, anxiety, anxious, depressed, homesick, overwhelmed, burnout, lonely, someone to talk to",
    category: "advising-counseling",
    officialUrl: "https://www.ncssm.edu/residential/safety-support/counseling/wellness-counseling",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "college-counseling",
    name: "College Counseling",
    description:
      "Your college counselor, application deadlines, transcript requests, and recommendation letter timelines.",
    aliases:
      "college applications, common app, college apps, recommendation letter, rec letter, sat, act, deadlines, early decision, where to apply",
    category: "advising-counseling",
    officialUrl: "https://www.ncssm.edu/residential/safety-support/counseling/college-career-planning",
    audience: "Juniors and seniors",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "academic-advising",
    name: "Academic advising",
    description:
      "Course selection, schedule changes, add/drop windows, and graduation requirement questions.",
    aliases:
      "schedule change, drop a class, add a class, course selection, registration, graduation requirements, credits, what classes to take",
    category: "advising-counseling",
    officialUrl: "https://www.ncssm.edu/residential/academics/courses",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ---------------------------------------------------- residential-life */
  {
    id: "residential-life",
    name: "Residential Life",
    description:
      "Who your RLA and Community Coordinator are, hall expectations, room changes, and how the residential day is structured.",
    aliases:
      "dorm, hall, rli, roommate, room change, curfew, lights out, residential, living on campus",
    category: "residential-life",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/housing-dining",
    contactNote:
      "Your hall is covered by RLAs (student leaders) and a Community Coordinator, the adult who lives next to the halls. Start with them for anything about the hall.",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "signout",
    name: "Sign-out & travel permissions",
    description:
      "Leaving campus, weekend travel, and parent permission. Submitted through the student information system.",
    aliases:
      "leave campus, sign out, signout, weekend, travel, going home, parent permission, off campus",
    category: "residential-life",
    officialUrl: "https://ncssm.myschoolapp.com",
    audience: "Residential students",
    loginRequired: true,
    platform: "blackbaud",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "maintenance-request",
    name: "Facilities & maintenance request",
    description:
      "Report a broken light, a stuck window, heating or cooling problems, and anything else physically wrong with your room or hall.",
    aliases:
      "broken, repair, fix, work order, heat, heating, ac, air conditioning, radiator, light out, leak, flooding, toilet, sink, facilities, laundry machine, dryer, washer",
    category: "residential-life",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/housing-dining",
    contactNote:
      "Your hall is covered by RLAs (student leaders) and a Community Coordinator, the adult who lives next to the halls. Start with them for anything about the hall.",
    audience: "Residential students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "laundry-mail",
    name: "Mail room & package pickup",
    description:
      "Where packages go, pickup hours, and how to address mail so it reaches you.",
    aliases:
      "package, packages, mail, amazon, delivery, mailroom, shipping address",
    category: "residential-life",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/housing-dining",
    contactNote:
      "Laundry rooms are in the residence halls and the machines take a small fee.",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ----------------------------------------------- dining-transportation */
  {
    id: "dining-menu",
    name: "Dining hall menus & hours",
    description:
      "What is being served, when the dining hall is open, and how to flag an allergy or dietary need.",
    aliases:
      "food, dining hall, cafeteria, menu, meal, meals, allergy, allergies, vegetarian, vegan, gluten, breakfast, lunch, dinner, dining hours",
    category: "dining-transportation",
    officialUrl: "https://www.ncssm.edu/residential/ncssm-durham/housing-dining",
    contactNote:
      "Meals are free to students. Vegetarian, vegan, and gluten-free options are provided; talk to dining staff about an allergy so it is on file.",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "bus-transportation",
    name: "Student transportation & break buses",
    description:
      "Bus schedules for breaks, pickup points across North Carolina, and how to reserve a seat.",
    aliases:
      "bus, buses, ride home, break bus, shuttle, getting home, travel home, pickup, drop off",
    category: "dining-transportation",
    officialUrl: "https://www.ncssm.edu/residential/campus-life",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "durham-transit",
    name: "GoDurham transit",
    description:
      "Public bus routes and live arrival times around Durham. Useful for getting to volunteering and community events off campus.",
    aliases:
      "godurham, city bus, public transit, bus route, getting around durham",
    category: "dining-transportation",
    officialUrl: "https://godurhamtransit.org",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* ---------------------------------------------------------- technology */
  {
    id: "it-helpdesk",
    name: "IT Help Desk",
    description:
      "Laptop problems, wifi that will not connect, printing, and account lockouts. Start here before anything else tech related.",
    aliases:
      "laptop, computer broken, wifi not working, internet down, printer, printing, password reset, locked out of my account, tech support, it help, charger",
    category: "technology",
    officialUrl: "https://www.ncssm.edu/information-technology-services",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "ncssm-email",
    name: "NCSSM email & Google Workspace",
    description:
      "Your school email, Drive, Docs, and Calendar. Navigate links you to Google's own sign-in; it never sees your password or your files.",
    aliases:
      "gmail, email, inbox, google drive, docs, sheets, slides, calendar, workspace",
    category: "technology",
    officialUrl: "https://mail.google.com",
    audience: "All students",
    loginRequired: true,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "blackbaud",
    name: "Student information system",
    description:
      "Schedule, attendance, report cards, and permissions. This is the system most official student records live in.",
    aliases:
      "myschoolapp, sis, student portal, report card, attendance, my schedule, grades, transcript view",
    category: "technology",
    officialUrl: "https://ncssm.myschoolapp.com",
    audience: "All students",
    loginRequired: true,
    platform: "blackbaud",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "wifi",
    name: "Campus wifi setup",
    description:
      "Which network to join, how to register a personal device, and what to do when a device keeps dropping off.",
    aliases:
      "internet, network, wifi password, connect to wifi, eduroam, register device, xbox, console, tv",
    category: "technology",
    officialUrl: "https://www.ncssm.edu/information-technology-services",
    audience: "Residential students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* --------------------------------------------------------------- forms */
  {
    id: "transcript-request",
    name: "Transcript request",
    description:
      "Request an official transcript for colleges, summer programs, and scholarship applications.",
    aliases:
      "transcript, official transcript, records, registrar, send my grades, school records",
    category: "forms",
    officialUrl: "https://registrar.ncssm.edu/",
    audience: "All students and alumni",
    loginRequired: true,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "club-charter",
    name: "Club charter & renewal form",
    description:
      "Start a new club or renew an existing one for the year, including advisor sign-off.",
    aliases:
      "start a club, new club, charter a club, club renewal, found a club",
    category: "forms",
    officialUrl: "https://www.ncssm.edu/residential/activities-clubs",
    audience: "Club officers",
    loginRequired: true,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "funding-request",
    name: "Student activity funding request",
    description:
      "Ask for funding for a club event, competition travel, or supplies. Read the deadline before you start.",
    aliases:
      "money, funding, budget, reimbursement, club money, pay for, buy supplies, travel funding",
    category: "forms",
    officialUrl: "https://www.ncssm.edu/residential/activities-clubs",
    audience: "Club officers",
    loginRequired: true,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* -------------------------------------------------------- student-life */
  {
    id: "clubs-directory",
    name: "Clubs & organizations",
    description:
      "The full list of chartered clubs, who leads them, and when they meet.",
    aliases:
      "clubs, organizations, activities, join a club, extracurriculars, what clubs exist",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/residential/activities-clubs",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "athletics",
    name: "Athletics & intramurals",
    description:
      "Team rosters, practice times, game schedules, and how to join an intramural league mid-season.",
    aliases:
      "sports, team, tryouts, gym, weight room, intramural, practice, workout, fitness",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/residential/durham-athletics",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "campus-calendar",
    name: "Campus calendar",
    description:
      "Academic dates, breaks, exam windows, and all-school events in one calendar.",
    aliases:
      "calendar, important dates, breaks, spring break, exams, finals, when is",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/about/events",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  /* -------------------------------------------------- student-government */
  {
    id: "sg-contact",
    name: "Contact Student Government",
    description:
      "Reach SG directly about anything Navigate does not cover, including things you would rather say to a person.",
    aliases:
      "student government, sg, senate, contact sg, talk to sg",
    category: "student-government",
    officialUrl: "/sg",
    audience: "All students",
    loginRequired: false,
    platform: "email",
    lastVerified: null,
    verificationStatus: "needs-review",
  },
  {
    id: "sg-report-issue",
    name: "Report an issue to SG",
    description:
      "Submit a concern about academics, housing, dining, transport, tech, or accessibility. You can submit anonymously.",
    aliases:
      "complain, complaint, report a problem, issue, suggestion, feedback, something is wrong",
    category: "student-government",
    officialUrl: "/report",
    audience: "All students",
    loginRequired: false,
    platform: "form",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "sg-updates-link",
    name: "SG issue status board",
    description:
      "See what SG is working on right now and where each item stands, without any private details.",
    aliases:
      "status, progress, what is sg doing, updates, is anyone fixing",
    category: "student-government",
    officialUrl: "/updates",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
  },

  /* ---------------------------------------------------- added from the
     NCSSM site's own page tree. Every URL here was opened and returned 200,
     but nobody at the school has confirmed each is the best destination for
     what the row promises, so they stay needs-review. */

  {
    id: "staff-directory",
    name: "Faculty & staff directory",
    description:
      "Search for any staff member and get their role and email. The fastest answer to “who do I actually email about this”.",
    aliases:
      "who do i email, contact a teacher, staff email, find a teacher, phone number, department contact, who handles",
    category: "student-government",
    officialUrl: "https://www.ncssm.edu/about/directory",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "wellness-counseling",
    name: "Wellness counseling",
    description:
      "The counseling team's page for ongoing mental-health support: what they do, who they are, and how to start.",
    aliases:
      "therapy, therapist, mental health, anxiety, depression, stress, counseling appointment, talk to someone, wellness",
    category: "advising-counseling",
    officialUrl:
      "https://www.ncssm.edu/residential/safety-support/counseling/wellness-counseling",
    contactNote:
      "For something that cannot wait out of hours, go to a Community Coordinator desk, or call or text 988.",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "accessibility-services",
    name: "Accessibility services",
    description:
      "Academic accommodations, documentation, and who to talk to about getting support in place.",
    aliases:
      "accommodations, 504, iep, extra time, testing accommodations, disability, accessibility, learning support, adhd",
    category: "advising-counseling",
    officialUrl:
      "https://www.ncssm.edu/residential/safety-support/counseling/accessibility",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "title-ix",
    name: "Title IX",
    description:
      "Reporting and support for sex discrimination, harassment, and sexual misconduct, including who the coordinator is.",
    aliases:
      "harassment, sexual harassment, assault, discrimination, title 9, report misconduct, coordinator",
    category: "urgent-support",
    officialUrl: "https://sites.google.com/a/ncssm.edu/ncssm-title-ix",
    contactNote:
      "This is a formal reporting route with people trained for it. Navigate is not, and an issue like this should never go through the report form.",
    audience: "All students",
    loginRequired: false,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "lgbtq-resources",
    name: "LGBTQ+ resource guide",
    description:
      "NCSSM's guide to support, groups, and points of contact for LGBTQ+ students.",
    aliases:
      "lgbtq, lgbt, queer, trans, transgender, gay, pronouns, gsa, support group, coming out",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/lgbtq-resource-guide",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "course-catalog",
    name: "Durham course catalog",
    description:
      "Every course offered on the Durham campus, with descriptions and prerequisites. Use it before registration, not after.",
    aliases:
      "courses, course catalog, what classes, prerequisites, class list, registration, pick classes, electives",
    category: "academic-support",
    officialUrl: "https://courses.ncssm.edu/course_catalog.php?id=1",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: true,
  },
  {
    id: "student-research",
    name: "Research & innovation",
    description:
      "Mentored research, the research course sequence, and how students get placed with a lab or mentor.",
    aliases:
      "research, lab, mentorship, mentor, science fair, independent study, publish, internship",
    category: "academic-support",
    officialUrl: "https://www.ncssm.edu/residential/academics/student-research",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "service-learning",
    name: "Service learning",
    description:
      "How NCSSM's service requirement works, what counts, and where to log hours.",
    aliases:
      "service hours, volunteering, community service, requirement, log hours, graduation requirement",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/residential/service-learning",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "student-media",
    name: "Student media",
    description:
      "The student publications and media groups, and how to join or submit to them.",
    aliases:
      "newspaper, yearbook, magazine, journalism, radio, podcast, photography, write for, submit",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/residential/student-media",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "fine-arts",
    name: "Fine arts",
    description:
      "Music, theatre, and visual arts at NCSSM: ensembles, productions, and how to take part.",
    aliases:
      "art, music, band, orchestra, choir, theatre, theater, drama, play, ensemble, audition, studio",
    category: "student-life",
    officialUrl: "https://sites.google.com/ncssm.edu/ncssmfinearts",
    audience: "All students",
    loginRequired: false,
    platform: "google",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "unc-guaranteed-admission",
    name: "UNC System guaranteed admission",
    description:
      "What NCSSM graduates are guaranteed within the UNC System, and the conditions attached.",
    aliases:
      "unc, guaranteed admission, in state college, state school, apply unc, chapel hill, nc state",
    category: "advising-counseling",
    officialUrl:
      "https://www.ncssm.edu/residential/unc-system-guaranteed-admission",
    audience: "Juniors and seniors",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "unc-tuition-grant",
    name: "UNC System tuition grant",
    description:
      "The tuition grant NCSSM graduates can receive at UNC System schools, and what qualifies.",
    aliases:
      "tuition grant, scholarship, financial aid, money for college, free tuition, pay for college",
    category: "advising-counseling",
    officialUrl: "https://www.ncssm.edu/residential/unc-system-tuition-grant",
    audience: "Juniors and seniors",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "college-credit",
    name: "College credit agreements",
    description:
      "Which NCSSM courses transfer for college credit and where those agreements apply.",
    aliases:
      "college credit, transfer credit, ap credit, dual enrollment, does this count, credit agreement",
    category: "academic-support",
    officialUrl:
      "https://www.ncssm.edu/residential/academics/college-credit-agreements",
    audience: "Juniors and seniors",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "emergency-procedures",
    name: "Emergency procedures & alerts",
    description:
      "What happens in a lockdown, tornado, or other emergency, plus the AED and emergency phone maps.",
    aliases:
      "emergency, lockdown, tornado, fire, evacuation, alert, aed, drill, severe weather, what do i do",
    category: "urgent-support",
    officialUrl: "https://www.ncssm.edu/contact/durham-emergency-info",
    contactNote:
      "Durham Campus Safety: 919-416-2911. Call 911 first if someone is in danger.",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
  {
    id: "spirit-store",
    name: "Spirit store",
    description:
      "Official NCSSM clothing and merchandise.",
    aliases: "merch, hoodie, sweatshirt, shirt, store, spirit wear, unicorns, gear",
    category: "student-life",
    officialUrl: "https://www.ncssm.edu/spirit-store",
    audience: "All students",
    loginRequired: false,
    platform: "web",
    lastVerified: null,
    verificationStatus: "needs-review",
    featured: false,
  },
];
