/**
 * Round-trip a content file between TypeScript and CSV.
 *
 *   node scripts/content-csv.mjs export <dataset> [out.csv]
 *   node scripts/content-csv.mjs import <dataset> <in.csv>
 *
 * Datasets: see DATASETS below.
 *
 * Same workflow as the resource directory: export to seed a Google Sheet, let
 * several people collect there at once, export the sheet back to CSV, import,
 * review the diff, commit. The TypeScript file stays the thing the app reads
 * and the thing code review sees; the spreadsheet is an editing surface, not a
 * second database.
 *
 * Table-driven rather than one script per dataset. Three near-identical
 * parsers would drift, and the one that drifts is the one that eats an
 * evening of someone's typing.
 *
 * Import validates every row and writes nothing at all if any row is bad.
 */

import { readFile, writeFile } from "node:fs/promises";
import { parseCsv, toCsv, truthy } from "./lib/csv.mjs";

const TAXONOMY = new URL("../src/content/taxonomy.ts", import.meta.url);

/**
 * Field kinds:
 *  - `id`      lowercase slug, unique, required
 *  - `string`  text; `emit: "when-set"` omits the line when empty
 *  - `enum`    validated against a taxonomy array named by `from`
 *  - `bool`    true / false
 *  - `tribool` true / false / null, where null means nobody has said
 *  - `long`    like `string`, emitted wrapped onto its own line
 */
const DATASETS = {
  discounts: {
    file: "../src/content/discounts.ts",
    exportName: "studentDiscounts",
    typeName: "StudentDiscount",
    fields: [
      { key: "id", kind: "id" },
      { key: "name", kind: "string", required: true },
      { key: "kind", kind: "string", required: true },
      { key: "category", kind: "enum", from: "DISCOUNT_CATEGORIES", required: true },
      // Allowed to be empty on purpose: an unknown discount must stay unknown.
      { key: "terms", kind: "string" },
      { key: "studentIdRequired", kind: "tribool" },
      { key: "mapsQuery", kind: "string", emit: "when-set" },
      { key: "aliases", kind: "long", emit: "when-set" },
    ],
  },
};

/* -------------------------------------------------------------- TS reading */

async function readTaxonomyIds(constName) {
  const text = await readFile(TAXONOMY, "utf8");
  const block = text.split(`export const ${constName} = [`)[1]?.split("] as const")[0];
  if (!block) throw new Error(`Could not find ${constName} in taxonomy.ts`);
  return [...block.matchAll(/id: "([^"]+)"/g)].map((m) => m[1]);
}

/**
 * Everything in the file that is not the array itself, kept verbatim.
 *
 * Two reasons. The doc comment above the array explains the editing rules, and
 * the resource script keeps its copy inside the script, so the rules live in
 * two places and only one of them gets read. And anything declared BELOW the
 * array - a shared-aliases constant, a helper - is real code that an import
 * would otherwise delete silently, which a round-trip test caught here on the
 * first run.
 */
function splitAround(text, exportName) {
  const marker = `export const ${exportName}`;
  const at = text.indexOf(marker);
  if (at === -1) throw new Error(`Could not find "export const ${exportName}".`);
  const end = text.indexOf("\n];\n", at);
  if (end === -1) throw new Error(`Could not find the end of ${exportName}.`);
  return { header: text.slice(0, at), footer: text.slice(end + "\n];\n".length) };
}

/**
 * Parse the array literal well enough to export it.
 *
 * Reads the literal rather than importing the module, because `node` cannot
 * import TypeScript without a build step and adding one for a maintenance
 * script is not worth it. Everything here is generated by `serialize` below or
 * hand-written to match it.
 */
function parseRecords(text, dataset) {
  const body = text.split(`export const ${dataset.exportName}`)[1];
  if (!body) throw new Error(`Could not find the ${dataset.exportName} array.`);

  const rows = [];
  for (const chunk of body.split(/\n  \{\n/).slice(1)) {
    const record = chunk.split(/\n  \},/)[0];

    const str = (key) => {
      const m = record.match(
        new RegExp(`(?:^|\\n)    ${key}:\\s*\\n?\\s*"((?:[^"\\\\]|\\\\.)*)"`),
      );
      if (!m) return "";
      try {
        return JSON.parse(`"${m[1]}"`);
      } catch {
        return m[1];
      }
    };
    const bool = (key) => new RegExp(`(?:^|\\n)    ${key}: true`).test(record);
    const tribool = (key) => {
      const m = record.match(new RegExp(`(?:^|\\n)    ${key}: (true|false|null)`));
      if (!m) return "";
      return m[1] === "null" ? "" : m[1] === "true" ? "yes" : "no";
    };

    const row = {};
    for (const field of dataset.fields) {
      row[field.key] =
        field.kind === "bool"
          ? bool(field.key)
          : field.kind === "tribool"
            ? tribool(field.key)
            : str(field.key);
    }
    if (!row.id) continue;
    rows.push(row);
  }
  return rows;
}

/* -------------------------------------------------------------- TS writing */

function serialize({ header, footer }, dataset, rows) {
  // JSON string syntax is a subset of TS string syntax, so this is safe for
  // quotes, backslashes, and newlines alike.
  const q = (value) => JSON.stringify(String(value));

  const record = (row) => {
    const lines = [];
    for (const field of dataset.fields) {
      const value = row[field.key];
      const when = field.emit ?? "always";

      if (field.kind === "bool") {
        lines.push(`    ${field.key}: ${value === true || value === "true"},`);
        continue;
      }
      if (field.kind === "tribool") {
        lines.push(`    ${field.key}: ${value === null ? "null" : value},`);
        continue;
      }
      if (when === "when-set" && !value) continue;
      if (field.kind === "long") {
        lines.push(`    ${field.key}:\n      ${q(value)},`);
        continue;
      }
      lines.push(`    ${field.key}: ${q(value ?? "")},`);
    }
    return `  {\n${lines.join("\n")}\n  },`;
  };

  return `${header}export const ${dataset.exportName}: ${dataset.typeName}[] = [
${rows.map(record).join("\n")}
];
${footer}`;
}

/* ------------------------------------------------------------------- main */

const [mode, name, arg] = process.argv.slice(2);
const dataset = DATASETS[name];

if (!dataset || (mode !== "export" && mode !== "import")) {
  console.error(
    `Usage: node scripts/content-csv.mjs export|import <dataset> [file]\n` +
      `Datasets: ${Object.keys(DATASETS).join(", ")}`,
  );
  process.exit(1);
}

const FILE = new URL(dataset.file, import.meta.url);
const columns = dataset.fields.map((field) => field.key);
const text = await readFile(FILE, "utf8");

if (mode === "export") {
  const rows = parseRecords(text, dataset);
  const out = arg ?? `${name}.csv`;
  await writeFile(out, toCsv(columns, rows), "utf8");
  console.log(`Exported ${rows.length} ${name} to ${out}`);
  console.log("Upload it to a Google Sheet, edit there, then export back to CSV.");
} else {
  if (!arg) {
    console.error(`Usage: node scripts/content-csv.mjs import ${name} <in.csv>`);
    process.exit(1);
  }

  // Enum vocabularies are read from taxonomy.ts so the spreadsheet can never
  // introduce a category the UI has no colour, label, or filter chip for.
  const enums = {};
  for (const field of dataset.fields) {
    if (field.kind === "enum") enums[field.key] = await readTaxonomyIds(field.from);
  }

  const grid = parseCsv(await readFile(arg, "utf8"));
  const header = grid[0].map((h) => h.trim());
  const missing = dataset.fields
    .filter((field) => field.kind === "id" || field.required)
    .map((field) => field.key)
    .filter((col) => !header.includes(col));
  if (missing.length) {
    console.error(`CSV is missing required column(s): ${missing.join(", ")}`);
    process.exit(1);
  }

  const errors = [];
  const seen = new Set();
  const rows = [];

  grid.slice(1).forEach((cells, index) => {
    const line = index + 2;
    const get = (col) => (cells[header.indexOf(col)] ?? "").trim();
    const bad = (message) => errors.push(`  line ${line}: ${message}`);
    const row = {};

    for (const field of dataset.fields) {
      const raw = get(field.key);

      if (field.kind === "id") {
        row.id = raw;
        if (!raw) bad("id is required");
        else if (!/^[a-z0-9][a-z0-9-]*$/.test(raw))
          bad(`id "${raw}" must be lowercase letters, digits, and hyphens`);
        else if (seen.has(raw)) bad(`duplicate id "${raw}"`);
        else seen.add(raw);
        continue;
      }

      if (field.kind === "bool") {
        row[field.key] = truthy(raw);
        continue;
      }

      if (field.kind === "tribool") {
        // Blank means nobody has said, which is a real answer here and must
        // not collapse into "no".
        if (!raw) row[field.key] = null;
        else if (/^(yes|y|true|1|x)$/i.test(raw)) row[field.key] = true;
        else if (/^(no|n|false|0)$/i.test(raw)) row[field.key] = false;
        else {
          row[field.key] = null;
          bad(`${field.key} "${raw}" must be yes, no, or empty for unknown`);
        }
        continue;
      }

      if (field.kind === "enum" && !enums[field.key].includes(raw)) {
        bad(
          `${field.key} "${raw}" is not in taxonomy.ts ` +
            `(${enums[field.key].join(", ")})`,
        );
      }
      if (field.required && !raw) bad(`${field.key} is required`);
      row[field.key] = raw;
    }

    rows.push(row);
  });

  if (errors.length) {
    console.error(`Refusing to import. ${errors.length} problem(s):\n`);
    console.error(errors.join("\n"));
    console.error("\nNothing was written. Fix the CSV and run again.");
    process.exit(1);
  }

  await writeFile(
    FILE,
    serialize(splitAround(text, dataset.exportName), dataset, rows),
    "utf8",
  );
  console.log(`Imported ${rows.length} ${name} into ${dataset.file.replace("../", "")}`);
  console.log("Next: git diff to review, then commit.");
}
